### ISSUE TITLE
As a cashier, I want to edit existing customer entries.

### ISSUE THREAD

**Issue by RiggiG** [cse442-fall-2019-offering/442projects-team-7#11]

**Comment by Se4musty** [comment]
**Edit an Existing Customer Acceptance Test**:

1.) From the login display, navigate to the box labeled 'Username:'. Click the box and type 'edmund'.

2.) Navigate to the box labeled 'Password:', click the box and type 'qwerty'.

3.) Navigate the 'Submit' button, click the button.

4.) The application should now have a new main window, with a button towards the upper-left portion of the screen labeled 'Customer Lookup'. Navigate to the 'Customer Lookup' button and click it.

5.) The application should now have a new popup window labeled 'Customer Lookup'. Navigate to the bottom-left corner of the 'Customer Lookup' window and you should see a button labeled 'Refresh Table'. Click the 'Refresh Table' button.

6.) The 'Customer Lookup' window's table should now be updated with our currently stored customer information. Navigate to the row of the 'Customer Lookup' table which has the column name 'Jane Doe', then click that corresponding row. The row should now be highlighted to indicate it has been selected.

7.) Navigate to the end of the 'Customer Name' column entry of 'Jane Doe' so that the cursor is at the end of her name and click. Delete her name by holding the backspace key until 'Jane Doe' is no longer visible. Enter the name 'Test Name'.

8.) Navigate to the bottom of the 'Customer Lookup' window (while the same row is still selected/highlighted) and you should see a button labeled 'Edit', then click the button. 

9.) Navigate to the bottom of the 'Customer Lookup' window (while the same row is still selected/highlighted) and you should see a button labeled 'Refresh Table', then click the button. 

**Success condition:** A row with the column entry of 'Test Name' for 'Customer Name' should still be present after editing the table. 

**Failure condition:** 'Jane Doe' is still displayed as the column entry for 'Customer Name' in the previously edited row.

**Comment by Se4musty** [comment]
**Delete a Customer Acceptance Test**:

1.) Complete the 'Edit an Existing Customer Acceptance Test' above.

2.) Navigate to the row of the 'Customer Lookup' table which has the column name 'Test Name', then click that corresponding row. The row should now be highlighted to indicate it has been selected.

3.) Navigate to the bottom of the 'Customer Lookup' window (while the same row is still selected/highlighted) and you should see a button labeled 'Delete', then click the button. 

4.) Navigate to the bottom of the 'Customer Lookup' window (while the same row is still selected/highlighted) and you should see a button labeled 'Refresh Table', then click the button. 

**Success condition:** The row which had the column entry of 'Test Name' for 'Customer Name' will be removed from the table.

**Failure condition:** 'Test Name' is still displayed as the column entry for 'Customer Name' in the previously edited row.
